######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 18 10:56:03 2012
######################################################################
QT       += core gui
TEMPLATE = app
TARGET = FilterSamesetBasic
DEPENDPATH += . build src ui
INCLUDEPATH += . src build

# Input
HEADERS += src/mainwidget.h
FORMS += ui/mainwidget.ui
SOURCES += src/main.cpp src/mainwidget.cpp
